<a href="https://colab.research.google.com/github/aneeshghisad/BTech-Project/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

In [30]:
from google.colab import files
uploaded = files.upload()

Saving milk_data_changed.csv to milk_data_changed (1).csv


In [31]:
milk = pd.read_csv('milk_data_changed.csv')

In [32]:
milk.head(5)

pH  Temprature  Odor  Turbidity  Colour   Grade
0  6.6          35     0          0     254    high
1  6.6          36     1          1     253    high
2  8.5          70     1          1     246     low
3  9.5          34     1          1     255     low
4  6.6          37     0          0     255  medium

In [33]:
# Check for missing data
print("Missing values:\n", milk.isnull().sum())

Missing values:
 pH            0
Temprature    0
Odor          0
Turbidity     0
Colour        0
Grade         0
dtype: int64


In [34]:
labels = milk.pop('Grade')

In [90]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(milk, labels, test_size=0.25,random_state=8)

In [91]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [92]:
from sklearn.linear_model import LogisticRegression

# Train logistic regression (multiclass)
reg = LogisticRegression(max_iter=10000, random_state=0, multi_class='multinomial')
reg.fit(x_train_scaled, y_train)
y_pred = reg.predict(x_test_scaled)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


In [93]:
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[27 18 22]
 [14 80 13]
 [ 0  7 84]]

Classification Report:
              precision    recall  f1-score   support

        high       0.66      0.40      0.50        67
         low       0.76      0.75      0.75       107
      medium       0.71      0.92      0.80        91

    accuracy                           0.72       265
   macro avg       0.71      0.69      0.68       265
weighted avg       0.72      0.72      0.71       265



In [94]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Calculate individual metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Accuracy: 0.720754716981132
Precision: 0.7087745667372641
Recall: 0.691241849701886
F1-score: 0.6849056603773586


In [95]:
sample = {
    'pH': 6.8,
    'Temprature': 45,
    'Odor': 1,
    'Turbidity': 0,
    'Colour': 254,
}

sample_df = pd.DataFrame([sample])

predicted_grade = reg.predict(sample_df)
print("Predicted Milk Grade:", predicted_grade[0])

Predicted Milk Grade: low


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
